database:
  host: localhost
  port: 3306
  name: minecraft
  user: root
  password: password
commands:
  pfchat: true
  pftag: true
  pffly: true
  pfvisibility: true
  pflang: true
  pfnick: true
  pfcolornick: true
  pfparty: true