name: PerfectPlayerSettings
version: '${project.version}'
main: hotfies.perfectplayersettings.PerfectPlayerSettings
api-version: '1.20'
load: STARTUP
authors: [Dem1ch, Aneras]
description: Settings for players
commands:
  pffly:
    description: Toggle fly mode
    usage: /pffly
  pfvisibility:
    description: Toggle player visibility
    usage: /pfvisibility
  pfchat:
    description: Toggle chat visibility
    usage: /pfchat
  pflang:
    description: Change language
    usage: /pflang <language>
  pftag:
    description: Set player tag
    usage: /pftag <tag>
  pfnick:
    description: Set player random nick
    usage: /pfnick
  pfcolornick:
    description: Set player color for nick
    usage: /pfcolornick <color>
  pfparty:
    description: Toggle party invites
    usage: /pfparty